
export const ADD_TO_CART = 'ADD_TO_CART';
export const CALCULATE_PRICE = 'CALCULATE_PRICE';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FALIED = 'FETCH_PRODUCTS_FALIED';

export const PURCHASE_PRODUCTS_START = 'PURCHASE_PRODUCTS_START';
export const PURCHASE_PRODUCTS_SUCCESS = 'PURCHASE_PRODUCTS_SUCCESS';
export const PURCHASE_PRODUCTS_FAILED = 'PURCHASE_PRODUCTS_FAILED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';